
---
 - name: install and start LAMP
   hosts: LAMP
   become: yes
  
   tasks:
   - name: install prerequisites
     apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

   - name: install Apache
     apt: name=apache2 update_cache=yes state=latest

   - name: install MySql
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'mysql-server', 'python3-pymysql' ]
   
   - name: install php
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'php', 'php-mysql', 'libapache2-mod-php' ]
